
package com.vidyo.portal.admin.v1_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VidyoPortalAdminServicePortType", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VidyoPortalAdminServicePortType {


    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetMembersResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getMembers")
    @WebResult(name = "GetMembersResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetMembersResponse getMembers(
        @WebParam(name = "GetMembersRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetMembersRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetMemberResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws MemberNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getMember")
    @WebResult(name = "GetMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetMemberResponse getMember(
        @WebParam(name = "GetMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetMemberRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, MemberNotFoundFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.AddMemberResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     * @throws MemberAlreadyExistsFault_Exception
     */
    @WebMethod(action = "addMember")
    @WebResult(name = "AddMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public AddMemberResponse addMember(
        @WebParam(name = "AddMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        AddMemberRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, MemberAlreadyExistsFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.UpdateMemberResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws MemberNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "updateMember")
    @WebResult(name = "UpdateMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public UpdateMemberResponse updateMember(
        @WebParam(name = "UpdateMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        UpdateMemberRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, MemberNotFoundFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.DeleteMemberResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws MemberNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "deleteMember")
    @WebResult(name = "DeleteMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public DeleteMemberResponse deleteMember(
        @WebParam(name = "DeleteMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        DeleteMemberRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, MemberNotFoundFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetRoomsResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRooms")
    @WebResult(name = "GetRoomsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetRoomsResponse getRooms(
        @WebParam(name = "GetRoomsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetRoomsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetRoomResponse
     * @throws RoomNotFoundFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRoom")
    @WebResult(name = "GetRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetRoomResponse getRoom(
        @WebParam(name = "GetRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.AddRoomResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws RoomAlreadyExistsFault_Exception
     * @throws GeneralFault_Exception
     * @throws InvalidModeratorPINFormatFault_Exception
     */
    @WebMethod(action = "addRoom")
    @WebResult(name = "AddRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public AddRoomResponse addRoom(
        @WebParam(name = "AddRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        AddRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, InvalidModeratorPINFormatFault_Exception, NotLicensedFault_Exception, RoomAlreadyExistsFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.UpdateRoomResponse
     * @throws RoomNotFoundFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws RoomAlreadyExistsFault_Exception
     * @throws InvalidModeratorPINFormatFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "updateRoom")
    @WebResult(name = "UpdateRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public UpdateRoomResponse updateRoom(
        @WebParam(name = "UpdateRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        UpdateRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, InvalidModeratorPINFormatFault_Exception, NotLicensedFault_Exception, RoomAlreadyExistsFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.DeleteRoomResponse
     * @throws RoomNotFoundFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "deleteRoom")
    @WebResult(name = "DeleteRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public DeleteRoomResponse deleteRoom(
        @WebParam(name = "DeleteRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        DeleteRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.EnableRoomResponse
     * @throws RoomNotFoundFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "enableRoom")
    @WebResult(name = "EnableRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public EnableRoomResponse enableRoom(
        @WebParam(name = "EnableRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        EnableRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.RoomIsEnabledResponse
     * @throws RoomNotFoundFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "roomIsEnabled")
    @WebResult(name = "RoomIsEnabledResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RoomIsEnabledResponse roomIsEnabled(
        @WebParam(name = "RoomIsEnabledRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RoomIsEnabledRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.EnableScheduledRoomResponse
     * @throws RoomNotFoundFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "enableScheduledRoom")
    @WebResult(name = "EnableScheduledRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public EnableScheduledRoomResponse enableScheduledRoom(
        @WebParam(name = "EnableScheduledRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        EnableScheduledRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.ScheduledRoomIsEnabledResponse
     * @throws RoomNotFoundFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "scheduledRoomIsEnabled")
    @WebResult(name = "ScheduledRoomIsEnabledResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public ScheduledRoomIsEnabledResponse scheduledRoomIsEnabled(
        @WebParam(name = "ScheduledRoomIsEnabledRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        ScheduledRoomIsEnabledRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetGroupsResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getGroups")
    @WebResult(name = "GetGroupsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetGroupsResponse getGroups(
        @WebParam(name = "GetGroupsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetGroupsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetGroupResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GroupNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getGroup")
    @WebResult(name = "GetGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetGroupResponse getGroup(
        @WebParam(name = "GetGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetGroupRequest parameter)
        throws GeneralFault_Exception, GroupNotFoundFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.AddGroupResponse
     * @throws GroupAlreadyExistsFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "addGroup")
    @WebResult(name = "AddGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public AddGroupResponse addGroup(
        @WebParam(name = "AddGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        AddGroupRequest parameter)
        throws GeneralFault_Exception, GroupAlreadyExistsFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.UpdateGroupResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GroupNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "updateGroup")
    @WebResult(name = "UpdateGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public UpdateGroupResponse updateGroup(
        @WebParam(name = "UpdateGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        UpdateGroupRequest parameter)
        throws GeneralFault_Exception, GroupNotFoundFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.DeleteGroupResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GroupNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "deleteGroup")
    @WebResult(name = "DeleteGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public DeleteGroupResponse deleteGroup(
        @WebParam(name = "DeleteGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        DeleteGroupRequest parameter)
        throws GeneralFault_Exception, GroupNotFoundFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetParticipantsResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getParticipants")
    @WebResult(name = "GetParticipantsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetParticipantsResponse getParticipants(
        @WebParam(name = "GetParticipantsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetParticipantsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetLectureModeParticipantsResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getLectureModeParticipants")
    @WebResult(name = "GetLectureModeParticipantsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetLectureModeParticipantsResponse getLectureModeParticipants(
        @WebParam(name = "GetLectureModeParticipantsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetLectureModeParticipantsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.InviteToConferenceResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "inviteToConference")
    @WebResult(name = "InviteToConferenceResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public InviteToConferenceResponse inviteToConference(
        @WebParam(name = "InviteToConferenceRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        InviteToConferenceRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.CancelOutboundCallResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "cancelOutboundCall")
    @WebResult(name = "CancelOutboundCallResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CancelOutboundCallResponse cancelOutboundCall(
        @WebParam(name = "CancelOutboundCallRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CancelOutboundCallRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.LeaveConferenceResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "leaveConference")
    @WebResult(name = "LeaveConferenceResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public LeaveConferenceResponse leaveConference(
        @WebParam(name = "LeaveConferenceRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        LeaveConferenceRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.MuteAudioResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "muteAudio")
    @WebResult(name = "MuteAudioResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public MuteAudioResponse muteAudio(
        @WebParam(name = "MuteAudioRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        MuteAudioRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.UnmuteAudioResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "unmuteAudio")
    @WebResult(name = "UnmuteAudioResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public UnmuteAudioResponse unmuteAudio(
        @WebParam(name = "UnmuteAudioRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        UnmuteAudioRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.StartVideoResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "startVideo")
    @WebResult(name = "StartVideoResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public StartVideoResponse startVideo(
        @WebParam(name = "StartVideoRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        StartVideoRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.StopVideoResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "stopVideo")
    @WebResult(name = "StopVideoResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public StopVideoResponse stopVideo(
        @WebParam(name = "StopVideoRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        StopVideoRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.CreatePublicRoomResponse
     * @throws PublicRoomCreationFault_Exception
     * @throws NotAllowedToCreateFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createPublicRoom")
    @WebResult(name = "CreatePublicRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreatePublicRoomResponse createPublicRoom(
        @WebParam(name = "CreatePublicRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreatePublicRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotAllowedToCreateFault_Exception, NotLicensedFault_Exception, PublicRoomCreationFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.CreateRoomURLResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createRoomURL")
    @WebResult(name = "CreateRoomURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateRoomURLResponse createRoomURL(
        @WebParam(name = "CreateRoomURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateRoomURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.RemoveRoomURLResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeRoomURL")
    @WebResult(name = "RemoveRoomURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveRoomURLResponse removeRoomURL(
        @WebParam(name = "RemoveRoomURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveRoomURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.CreateRoomPINResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createRoomPIN")
    @WebResult(name = "CreateRoomPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateRoomPINResponse createRoomPIN(
        @WebParam(name = "CreateRoomPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateRoomPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.RemoveRoomPINResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeRoomPIN")
    @WebResult(name = "RemoveRoomPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveRoomPINResponse removeRoomPIN(
        @WebParam(name = "RemoveRoomPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveRoomPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetLicenseDataResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getLicenseData")
    @WebResult(name = "GetLicenseDataResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetLicenseDataResponse getLicenseData(
        @WebParam(name = "GetLicenseDataRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetLicenseDataRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetPortalVersionResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getPortalVersion")
    @WebResult(name = "GetPortalVersionResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetPortalVersionResponse getPortalVersion(
        @WebParam(name = "GetPortalVersionRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetRecordingProfilesResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRecordingProfiles")
    @WebResult(name = "GetRecordingProfilesResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetRecordingProfilesResponse getRecordingProfiles(
        @WebParam(name = "GetRecordingProfilesRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.StartRecordingResponse
     * @throws ResourceNotAvailableFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "startRecording")
    @WebResult(name = "StartRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public StartRecordingResponse startRecording(
        @WebParam(name = "StartRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        StartRecordingRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, ResourceNotAvailableFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.PauseRecordingResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "pauseRecording")
    @WebResult(name = "PauseRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public PauseRecordingResponse pauseRecording(
        @WebParam(name = "PauseRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        PauseRecordingRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.ResumeRecordingResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "resumeRecording")
    @WebResult(name = "ResumeRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public ResumeRecordingResponse resumeRecording(
        @WebParam(name = "ResumeRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        ResumeRecordingRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.StopRecordingResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "stopRecording")
    @WebResult(name = "StopRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public StopRecordingResponse stopRecording(
        @WebParam(name = "StopRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        StopRecordingRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetLocationTagsResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getLocationTags")
    @WebResult(name = "GetLocationTagsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetLocationTagsResponse getLocationTags(
        @WebParam(name = "GetLocationTagsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetLocationTagsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetWebcastURLResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getWebcastURL")
    @WebResult(name = "GetWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetWebcastURLResponse getWebcastURL(
        @WebParam(name = "GetWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetWebcastURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.CreateWebcastURLResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createWebcastURL")
    @WebResult(name = "CreateWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateWebcastURLResponse createWebcastURL(
        @WebParam(name = "CreateWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateWebcastURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.RemoveWebcastURLResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeWebcastURL")
    @WebResult(name = "RemoveWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveWebcastURLResponse removeWebcastURL(
        @WebParam(name = "RemoveWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveWebcastURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.CreateWebcastPINResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createWebcastPIN")
    @WebResult(name = "CreateWebcastPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateWebcastPINResponse createWebcastPIN(
        @WebParam(name = "CreateWebcastPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateWebcastPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.RemoveWebcastPINResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeWebcastPIN")
    @WebResult(name = "RemoveWebcastPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveWebcastPINResponse removeWebcastPIN(
        @WebParam(name = "RemoveWebcastPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveWebcastPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetRoomProfilesResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRoomProfiles")
    @WebResult(name = "GetRoomProfilesResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetRoomProfilesResponse getRoomProfiles(
        @WebParam(name = "GetRoomProfilesRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetRoomProfileResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRoomProfile")
    @WebResult(name = "GetRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetRoomProfileResponse getRoomProfile(
        @WebParam(name = "GetRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetRoomProfileRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.SetRoomProfileResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "setRoomProfile")
    @WebResult(name = "SetRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public SetRoomProfileResponse setRoomProfile(
        @WebParam(name = "SetRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        SetRoomProfileRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.RemoveRoomProfileResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeRoomProfile")
    @WebResult(name = "RemoveRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveRoomProfileResponse removeRoomProfile(
        @WebParam(name = "RemoveRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveRoomProfileRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.CreateModeratorPINResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws InvalidModeratorPINFormatFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createRoomModeratorPIN")
    @WebResult(name = "CreateModeratorPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateModeratorPINResponse createModeratorPIN(
        @WebParam(name = "CreateModeratorPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateModeratorPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, InvalidModeratorPINFormatFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.RemoveModeratorPINResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeRoomModeratorPIN")
    @WebResult(name = "RemoveModeratorPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveModeratorPINResponse removeModeratorPIN(
        @WebParam(name = "RemoveModeratorPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveModeratorPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetConferenceIDResponse
     * @throws InPointToPointCallFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getConferenceID")
    @WebResult(name = "GetConferenceIDResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetConferenceIDResponse getConferenceID(
        @WebParam(name = "GetConferenceIDRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetConferenceIDRequest parameter)
        throws GeneralFault_Exception, InPointToPointCallFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.ScheduledRoomEnabledResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "isScheduledRoomEnabled")
    @WebResult(name = "ScheduledRoomEnabledResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public ScheduledRoomEnabledResponse isScheduledRoomEnabled(
        @WebParam(name = "ScheduledRoomEnabledRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.DisableScheduledRoomResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "disableScheduledRoom")
    @WebResult(name = "DisableScheduledRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public DisableScheduledRoomResponse disableScheduledRoom(
        @WebParam(name = "DisableScheduledRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        DisableScheduledRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.CreateScheduledRoomResponse
     * @throws ScheduledRoomCreationFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws InvalidModeratorPINFormatFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createScheduledRoom")
    @WebResult(name = "CreateScheduledRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateScheduledRoomResponse createScheduledRoom(
        @WebParam(name = "CreateScheduledRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateScheduledRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, InvalidModeratorPINFormatFault_Exception, NotLicensedFault_Exception, ScheduledRoomCreationFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.DeleteScheduledRoomResponse
     * @throws RoomNotFoundFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "deleteScheduledRoom")
    @WebResult(name = "DeleteScheduledRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public DeleteScheduledRoomResponse deleteScheduledRoom(
        @WebParam(name = "DeleteScheduledRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        DeleteScheduledRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.SetChatStateAdminResponse
     * @throws NotLicensedFault_Exception
     * @throws ChatNotAvailableInSuperFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "setChatStateAdmin")
    @WebResult(name = "setChatStateAdminResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public SetChatStateAdminResponse setChatStateAdmin(
        @WebParam(name = "setChatStateAdminRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        SetChatStateAdminRequest parameter)
        throws ChatNotAvailableInSuperFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.StartLectureModeResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "startLectureMode")
    @WebResult(name = "StartLectureModeResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public StartLectureModeResponse startLectureMode(
        @WebParam(name = "StartLectureModeRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        StartLectureModeRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.StopLectureModeResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "stopLectureMode")
    @WebResult(name = "StopLectureModeResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public StopLectureModeResponse stopLectureMode(
        @WebParam(name = "StopLectureModeRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        StopLectureModeRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.DismissRaisedHandResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "dismissRaisedHand")
    @WebResult(name = "DismissRaisedHandResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public DismissRaisedHandResponse dismissRaisedHand(
        @WebParam(name = "DismissRaisedHandRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        DismissRaisedHandRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.DismissAllRaisedHandResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "dismissAllRaisedHand")
    @WebResult(name = "DismissAllRaisedHandResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public DismissAllRaisedHandResponse dismissAllRaisedHand(
        @WebParam(name = "DismissAllRaisedHandRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        DismissAllRaisedHandRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.SetPresenterResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "setPresenter")
    @WebResult(name = "SetPresenterResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public SetPresenterResponse setPresenter(
        @WebParam(name = "SetPresenterRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        SetPresenterRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.RemovePresenterResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removePresenter")
    @WebResult(name = "RemovePresenterResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemovePresenterResponse removePresenter(
        @WebParam(name = "RemovePresenterRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemovePresenterRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.SetTenantRoomAttributesResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "setTenantRoomAttributes")
    @WebResult(name = "SetTenantRoomAttributesResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public SetTenantRoomAttributesResponse setTenantRoomAttributes(
        @WebParam(name = "SetTenantRoomAttributesRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        SetTenantRoomAttributesRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetTenantDetailsResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getTenantDetails")
    @WebResult(name = "GetTenantDetailsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetTenantDetailsResponse getTenantDetails(
        @WebParam(name = "GetTenantDetailsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetTenantDetailsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.TransferParticipantResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "transferParticipant")
    @WebResult(name = "TransferParticipantResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public TransferParticipantResponse transferParticipant(
        @WebParam(name = "TransferParticipantRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        TransferParticipantRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.SetLayoutResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "setLayout")
    @WebResult(name = "SetLayoutResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public SetLayoutResponse setLayout(
        @WebParam(name = "SetLayoutRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        SetLayoutRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.SearchMembersResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "searchMembers")
    @WebResult(name = "SearchMembersResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public SearchMembersResponse searchMembers(
        @WebParam(name = "SearchMembersRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        SearchMembersRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * 	          Allows for adding an additional client version at the super level. This new client version will be seen by all tenants. The new client version will not be activated.
     * 	      
     * 
     * @param parameters
     * @return
     *     returns com.vidyo.portal.admin.v1_1.AddClientVersionResponse
     * @throws ExternalModeFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "addClientVersion")
    @WebResult(name = "addClientVersionResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameters")
    public AddClientVersionResponse addClientVersion(
        @WebParam(name = "addClientVersionRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameters")
        AddClientVersionRequest parameters)
        throws ExternalModeFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception
    ;

    /**
     * 
     * 	          For adding new end point behavior at tenant level
     * 	      
     * 
     * @param parameters
     * @return
     *     returns com.vidyo.portal.admin.v1_1.CreateEndpointBehaviorResponse
     * @throws EndpointBehaviorDisabledFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws EndpointBehaviorAlreadyExistsFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createEndpointBehavior")
    @WebResult(name = "createEndpointBehaviorResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameters")
    public CreateEndpointBehaviorResponse createEndpointBehavior(
        @WebParam(name = "createEndpointBehaviorRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameters")
        CreateEndpointBehaviorRequest parameters)
        throws EndpointBehaviorAlreadyExistsFault_Exception, EndpointBehaviorDisabledFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception
    ;

    /**
     * 
     * 	          For updating end point behavior at tenant level
     * 	      
     * 
     * @param parameters
     * @return
     *     returns com.vidyo.portal.admin.v1_1.UpdateEndpointBehaviorResponse
     * @throws EndpointBehaviorDisabledFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     * @throws NoEndpointBehaviorExistsFault_Exception
     */
    @WebMethod(action = "updateEndpointBehavior")
    @WebResult(name = "updateEndpointBehaviorResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameters")
    public UpdateEndpointBehaviorResponse updateEndpointBehavior(
        @WebParam(name = "updateEndpointBehaviorRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameters")
        UpdateEndpointBehaviorRequest parameters)
        throws EndpointBehaviorDisabledFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NoEndpointBehaviorExistsFault_Exception
    ;

    /**
     * 
     * 	          For deleting end point behavior at tenant level
     * 	      
     * 
     * @param parameters
     * @return
     *     returns com.vidyo.portal.admin.v1_1.DeleteEndpointBehaviorResponse
     * @throws EndpointBehaviorDisabledFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NoEndpointBehaviorExistsFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "deleteEndpointBehavior")
    @WebResult(name = "deleteEndpointBehaviorResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameters")
    public DeleteEndpointBehaviorResponse deleteEndpointBehavior(
        @WebParam(name = "deleteEndpointBehaviorRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameters")
        DeleteEndpointBehaviorRequest parameters)
        throws EndpointBehaviorDisabledFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NoEndpointBehaviorExistsFault_Exception
    ;

    /**
     * 
     * 	          To Fetch end point behavior at tenant level
     * 	      
     * 
     * @param parameters
     * @return
     *     returns com.vidyo.portal.admin.v1_1.GetEndpointBehaviorResponse
     * @throws EndpointBehaviorDisabledFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NoEndpointBehaviorExistsFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getEndpointBehavior")
    @WebResult(name = "getEndpointBehaviorResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameters")
    public GetEndpointBehaviorResponse getEndpointBehavior(
        @WebParam(name = "getEndpointBehaviorRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameters")
        GetEndpointBehaviorRequest parameters)
        throws EndpointBehaviorDisabledFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, NoEndpointBehaviorExistsFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.portal.admin.v1_1.SearchRoomsResponse
     * @throws NotLicensedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "searchRooms")
    @WebResult(name = "SearchRoomsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public SearchRoomsResponse searchRooms(
        @WebParam(name = "SearchRoomsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        SearchRoomsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

}
